version: '3.8'

services:
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    ports:
      - "8080:8080"
    environment:
      TIME_ADDITION_MS: 100
      TIME_SUBTRACTION_MS: 100
      TIME_MULTIPLICATIONS_MS: 100
      TIME_DIVISIONS_MS: 100

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    environment:
      TIME_ADDITION_MS: 100
      TIME_SUBTRACTION_MS: 100
      TIME_MULTIPLICATIONS_MS: 100
      TIME_DIVISIONS_MS: 100
      COMPUTING_POWER: 5
    depends_on:
      - orchestrator
