# Используем официальный образ Go
FROM golang:1.23 AS builder

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем go.mod и go.sum
COPY go.mod go.sum ./

# Загружаем зависимости
RUN go mod download

# Копируем все остальные файлы
COPY . .

# Собираем агента
RUN go build -o agent ./cmd/agent

# Используем минимальный образ для запуска
FROM alpine:latest

# Копируем собранный бинарник из предыдущего шага
COPY --from=builder /app/agent /usr/local/bin/agent

# Устанавливаем переменные окружения
ENV TIME_ADDITION_MS=100
ENV TIME_SUBTRACTION_MS=100
ENV TIME_MULTIPLICATIONS_MS=100
ENV TIME_DIVISIONS_MS=100
ENV COMPUTING_POWER=5

# Запускаем агента
CMD ["agent"]
