version: "3.8"
services:
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - ./web:/app/web
    environment:
      - TIME_ADDITION_MS=200
      - TIME_SUBTRACTION_MS=200
      - TIME_MULTIPLICATIONS_MS=300
      - TIME_DIVISIONS_MS=400
      - ORCHESTRATOR_GRPC_ADDR=orchestrator:5000

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    depends_on:
      - orchestrator
    environment:
      - COMPUTING_POWER=4
      - ORCHESTRATOR_GRPC_ADDR=orchestrator:5000